### ISSUE TITLE
luminance redefinition shader error with r152 with the dithering changes

### ISSUE THREAD

**Issue by vincentfretin** [supermedium/aframe-environment-component#87]
@mrxz I don't know enough to fix this one, so I'm creating an issue.
With the changes in #82 and aframe master (r152)
in index.html change to:
```
<script src="https://cdn.jsdelivr.net/gh/aframevr/aframe@master/dist/aframe-master.min.js"></script>
```
and select the default environment you get the following shader error
```
three.module.js:18995 THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Program Info Log: Fragment shader is not compiled.

FRAGMENT

ERROR: 0:170: 'luminance' : redefinition
ERROR: 0:258: 'luminance' : variable expected
WARNING: 0:258: '/' : Divide by zero during constant folding
ERROR: 0:261: 'luminance' : variable expected
WARNING: 0:261: '/' : Divide by zero during constant folding

  165: #endif
  166: uniform sampler2D skySampler;
  167: uniform vec3 sunPosition;
  168: varying vec3 vWorldPosition;
  169: vec3 cameraPos = vec3(0., 0., 0.);
> 170: uniform float luminance;
```

if you revert the changes in #82 it fixes the error.

**Comment by mrxz** [comment]
Seems to be caused by a name collision. Three.js renamed one of their helper functions in the `common` shader chunk. The `common` chunk is needed for the dithering. See https://github.com/mrdoob/three.js/pull/24347

I created a PR (#88) addressing this issue by replacing `luminance` with a slightly different (and IMO more intuitive) `exposureBias`. By default the output is identical. Technically this would break for anyone who manually adjusted the value of this uniform, but I highly doubt anyone did. You can't even set it through the environment component directly (nor with a preset).

The shader itself is in pretty rough shape, I noticed quite a few typos and a bunch of uncommented magic constants floating around. The original `luminance` uniform also didn't actually seem to be "luminance" and would be difficult to tweak for artist as it behaves very counter-intuitive, non-linear, only valid in the range from 0.0 to ~1.2, and lower values result in higher exposure.

**Comment by vincentfretin** [comment]
Thank you for investigating this!

**Comment by vincentfretin** [comment]
Actually the error was in aframe 1.4.2 (r147), the current master build used in the index.html file is actually aframe 1.3.0 fyi.
